version: '3.8'

services:
  mariadb:
    image: mariadb:11.3
    container_name: mariadb_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: proyectoFinal
      MYSQL_USER: usuario
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
